androidannotations/androidannotations

AndroidAnnotations/androidannotations-api/src/main/java/org/androidannotations/api/sharedpreferences/AbstractPrefField.java
AndroidAnnotations/androidannotations-api/src/main/java/org/androidannotations/api/sharedpreferences/BooleanPrefField.java
AndroidAnnotations/androidannotations-api/src/main/java/org/androidannotations/api/sharedpreferences/FloatPrefField.java
AndroidAnnotations/androidannotations-api/src/main/java/org/androidannotations/api/sharedpreferences/IntPrefField.java
AndroidAnnotations/androidannotations-api/src/main/java/org/androidannotations/api/sharedpreferences/LongPrefField.java
AndroidAnnotations/androidannotations-api/src/main/java/org/androidannotations/api/sharedpreferences/StringPrefField.java
AndroidAnnotations/androidannotations-api/src/main/java/org/androidannotations/api/sharedpreferences/StringSetPrefField.java

#1203: Modified AbstractPrefField interface to include generic get and put methods.

---

AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/holder/InstanceStateHolder.java
AndroidAnnotations/functional-test-1-5/src/main/java/org/androidannotations/test15/instancestate/SaveInstanceStateActivity.java
AndroidAnnotations/functional-test-1-5/src/test/java/org/androidannotations/test15/instancestate/SaveInstanceStateActivityTest.java

1324 instance state stackoverflow

---

AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/handler/EIntentServiceHandler.java

Add constructor validation to @EIntentService

---

AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/handler/AnnotationHandlers.java

Move BeanHandler before menu handlers

---

AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/handler/ReceiverHandler.java
AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/holder/EActivityHolder.java
AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/holder/EFragmentHolder.java
AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/holder/EServiceHolder.java
AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/holder/HasReceiverRegistration.java
AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/holder/ReceiverRegistrationHolder.java
AndroidAnnotations/functional-test-1-5/src/main/java/org/androidannotations/test15/receiver/FragmentWithReceiver.java
AndroidAnnotations/functional-test-1-5/src/test/java/org/androidannotations/test15/receiver/FragmentWithReceiverTest.java

see https://github.com/excilys/androidannotations/issues/1132

fix receiver registered at onAttach

---

AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/handler/RoboGuiceHandler.java
AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/helper/CanonicalNameConstants.java
AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/helper/ValidatorHelper.java
AndroidAnnotations/functional-test-1-5/pom.xml
AndroidAnnotations/functional-test-1-5/src/test/java/org/androidannotations/test15/roboguice/RobolectricSampleTestModule.java
AndroidAnnotations/functional-test-1-5/src/test/java/org/androidannotations/test15/roboguice/TestSampleRoboApplication_.java

Integrate with RoboGuice 3

---

AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/handler/OptionsItemHandler.java
AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/holder/EActivityHolder.java
AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/holder/EFragmentHolder.java
AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/holder/HasOptionsMenu.java
AndroidAnnotations/functional-test-1-5/src/main/java/org/androidannotations/test15/menu/OptionsMenuActivity.java
AndroidAnnotations/functional-test-1-5/src/test/java/org/androidannotations/test15/menu/OptionsMenuActivityTest.java

Implements #1067.
@yDelouis i think this may be a breaking change, as clients could rely on the old behavior in their apps.

Allow subclasses to override @OptionsItem handling

---

AndroidAnnotations/androidannotations-api/src/main/java/org/androidannotations/api/sharedpreferences/SharedPreferencesCompat.java
AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/handler/SharedPrefHandler.java
AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/process/ProcessHolder.java
AndroidAnnotations/functional-test-1-5/src/test/java/org/androidannotations/test15/prefs/PrefsActivityTest.java

Return empty set as @DefaultStringSet default value

---

AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/holder/FoundViewHolder.java
AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/holder/GeneratedClassHolderDecorator.java
AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/holder/OnSeekBarChangeListenerHolder.java
AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/holder/ReceiverRegistrationHolder.java
AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/holder/RoboGuiceHolder.java
AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/holder/TextWatcherHolder.java

This PR contains one commit which was split off from #1294.

Refactor holders which decorate another holder

---

AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/handler/ItemClickHandler.java
AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/handler/ItemLongClickHandler.java
AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/handler/RoboGuiceHandler.java
AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/handler/ViewByIdHandler.java
AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/helper/APTCodeModelHelper.java
AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/helper/BundleHelper.java
AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/holder/EComponentWithViewSupportHolder.java
AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/holder/EViewHolder.java
AndroidAnnotations/androidannotations/src/test/java/org/androidannotations/viewbyid/GenericViewByIdActivity.java
AndroidAnnotations/androidannotations/src/test/java/org/androidannotations/viewbyid/R.java
AndroidAnnotations/androidannotations/src/test/java/org/androidannotations/viewbyid/ViewByIdTest.java
AndroidAnnotations/androidannotations/src/test/resources/org/androidannotations/viewbyid/AndroidManifest.xml

Fix for @ViewById generic issues

---

AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/helper/ValidatorHelper.java

Allow abstract @EApplication not registered in the manifest

---

AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/handler/RoboGuiceHandler.java
AndroidAnnotations/functional-test-1-5/src/main/java/org/androidannotations/test15/roboguice/ActivityWithRoboGuice.java

Fix RoboGuice listener field injections

---

AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/holder/InstanceStateHolder.java
AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/holder/OnActivityResultHolder.java

I left out two holders in the previous PR.

Refactor more holder decorators

---

AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/handler/SystemServiceHandler.java
AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/helper/CanonicalNameConstants.java
AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/process/ProcessHolder.java
AndroidAnnotations/functional-test-1-5/src/main/java/org/androidannotations/test15/ActivityWithServices.java
AndroidAnnotations/functional-test-1-5/src/test/java/org/androidannotations/test15/ServiceInjectionTest.java

Handle special case when injecting AppWidgetManager with @SystemService

---

AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/handler/AbstractSeekBarTouchHandler.java
AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/handler/AfterExtrasHandler.java
AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/handler/AfterInjectHandler.java
AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/handler/AfterPreferencesHandler.java
AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/handler/AfterTextChangeHandler.java
AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/handler/AfterViewsHandler.java
AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/handler/CheckedChangeHandler.java
AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/handler/ClickHandler.java
AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/handler/EditorActionHandler.java
AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/handler/FocusChangeHandler.java
AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/handler/ItemClickHandler.java
AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/handler/ItemLongClickHandler.java
AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/handler/ItemSelectHandler.java
AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/handler/LongClickHandler.java
AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/handler/OnActivityResultHandler.java
AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/handler/OptionsItemHandler.java
AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/handler/PreferenceChangeHandler.java
AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/handler/PreferenceClickHandler.java
AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/handler/ProduceHandler.java
AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/handler/ReceiverActionHandler.java
AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/handler/ReceiverHandler.java
AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/handler/SubscribeHandler.java
AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/handler/TouchHandler.java
AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/handler/TransactionalHandler.java
AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/helper/ValidatorParameterHelper.java

Implements #1284.
This is only a WIP, but i am sharing the work, to get an early response about the direction, @yDelouis @dodgex.

ValidatorParameterHelper fluent API

---

AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/handler/ResHandler.java
AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/helper/CanonicalNameConstants.java
AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/process/ProcessHolder.java
AndroidAnnotations/androidannotations/src/test/java/org/androidannotations/generation/ActivityWithDrawable.java
AndroidAnnotations/androidannotations/src/test/java/org/androidannotations/generation/ContextCompatDrawableTest.java
AndroidAnnotations/androidannotations/src/test/java/org/androidannotations/generation/R.java
AndroidAnnotations/androidannotations/src/test/resources/org/androidannotations/generation/AndroidManifestForDrawable.xml
AndroidAnnotations/androidannotations/src/test/resources/org/androidannotations/generation/ContextCompat.java

If ContextCompat is available, use it to resolve drawables

---

AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/helper/AnnotationHelper.java
AndroidAnnotations/functional-test-1-5/src/main/java/org/androidannotations/test15/SeekBarChangeListenedActivity.java
AndroidAnnotations/functional-test-1-5/src/test/java/org/androidannotations/test15/SeekBarChangeListenedActivityTest.java

Fix wrong @SeekBarTouchStop naming convention

---

AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/handler/rest/RestMethodHandler.java

Do not add extra block in @Rest methods

---

AndroidAnnotations/androidannotations-api/src/main/java/org/androidannotations/annotations/OrmLiteDao.java
AndroidAnnotations/functional-test-1-5/src/main/java/org/androidannotations/test15/eservice/MySimpleIntentService.java

according to the [wiki](https://github.com/excilys/androidannotations/wiki/Ormlite) this should have been gone already. ;)

remove model parameter from @OrmLiteDao

---

AndroidAnnotations/androidannotations-api/src/main/java/org/androidannotations/annotations/ReceiverAction.java
AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/handler/ReceiverActionHandler.java
AndroidAnnotations/functional-test-1-5/src/main/java/org/androidannotations/test15/ereceiver/ReceiverWithActions.java

implements issue https://github.com/excilys/androidannotations/issues/1235
based on PR https://github.com/excilys/androidannotations/pull/1234 
do not merge before 4.0

1235 do not use methodname as action

---

AndroidAnnotations/functional-test-1-5/.factorypath
AndroidAnnotations/functional-test-1-5/.gitignore
AndroidAnnotations/functional-test-1-5/.settings/org.eclipse.jdt.apt.core.prefs

Re-add Eclipse APT settings

---

AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/handler/OptionsMenuItemHandler.java
AndroidAnnotations/androidannotations/src/test/java/org/androidannotations/menu/OptionsMenuItemActivity.java
AndroidAnnotations/androidannotations/src/test/java/org/androidannotations/menu/OptionsMenuItemTest.java
AndroidAnnotations/androidannotations/src/test/java/org/androidannotations/menu/R.java
AndroidAnnotations/androidannotations/src/test/resources/org/androidannotations/menu/AndroidManifest.xml

`@OptionsMenuItem` field's name can be same as method parameter's name

Bugfix @OptionsMenuItem field naming

---

AndroidAnnotations/androidannotations-api/src/main/java/org/androidannotations/annotations/InjectMenu.java
AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/handler/AnnotationHandlers.java
AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/handler/InjectMenuHandler.java
AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/helper/ValidatorHelper.java
AndroidAnnotations/androidannotations/src/test/java/org/androidannotations/menu/InjectMenuActivity.java
AndroidAnnotations/androidannotations/src/test/java/org/androidannotations/menu/InjectMenuTest.java
AndroidAnnotations/androidannotations/src/test/resources/org/androidannotations/menu/AndroidManifest.xml
AndroidAnnotations/functional-test-1-5/src/main/AndroidManifest.xml
AndroidAnnotations/functional-test-1-5/src/main/java/org/androidannotations/test15/menu/InjectMenuActivity.java
AndroidAnnotations/functional-test-1-5/src/test/java/org/androidannotations/test15/menu/InjectMenuActivityTest.java

Add @InjectMenu to inject a menu

---

AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/handler/FragmentArgHandler.java
AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/handler/rest/RestServiceHandler.java
AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/helper/APTCodeModelHelper.java
AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/holder/BaseGeneratedClassHolder.java
AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/holder/EBeanHolder.java
AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/holder/EFragmentHolder.java
AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/holder/EViewHolder.java
AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/holder/RestHolder.java
AndroidAnnotations/androidannotations/src/test/java/org/androidannotations/rest/GenericClient.java
AndroidAnnotations/androidannotations/src/test/java/org/androidannotations/rest/GenericClientHolderBean.java
AndroidAnnotations/androidannotations/src/test/java/org/androidannotations/rest/RestServiceTest.java

Fixes generic issues raised in #1402 and #1403.

Fix generic issues

---

AndroidAnnotations/pom.xml

Yet another task which should have been automated long time ago. :)
This is a WIP PR, cannot be merged now, because it depends on changes from another PR (#1455). But if that is merged, i will rebase this and this will be ready to merged, too. The interesting commit is the last here.

Check license headers in Travis

---

.travis.yml

This needs `GITTER_WEBHOOK_URL` variable added in Travis settings.
@yDelouis if you are OK with this i merge and add that.

Add Gitter notifications from Travis

---

AndroidAnnotations/androidannotations-core/androidannotations-testutils/src/main/java/org/androidannotations/testutils/AAProcessorTestHelper.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/helper/CanonicalNameConstants.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/WindowFeatureHandler.java
AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/generation/WindowFeatureAppCompatActivityTest.java
AndroidAnnotations/androidannotations-core/androidannotations/src/test/resources/org/androidannotations/generation/AndroidManifest.xml
AndroidAnnotations/androidannotations-core/androidannotations/src/test/resources/org/androidannotations/generation/WindowFeatureAppCompatActivity.java
AndroidAnnotations/androidannotations-core/androidannotations/src/test/resources/org/androidannotations/generation/support/AppCompatActivity.java

@WindowFeature uses correct method when using support library

---

AndroidAnnotations/androidannotations-core/androidannotations-test/src/test/java/org/androidannotations/test/afterextras/AfterExtrasActivityTest.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/AfterExtrasHandler.java

see https://github.com/excilys/androidannotations/issues/1528

always call methods with @AfterExtras annotation

---

AndroidAnnotations/androidannotations-rest-spring/rest-spring-api/src/main/java/org/androidannotations/rest/spring/annotations/Rest.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring-test/src/main/java/org/androidannotations/rest/spring/test/MyResponseErrorHandler.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring-test/src/main/java/org/androidannotations/rest/spring/test/MyResponseErrorHandlerBean.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring-test/src/main/java/org/androidannotations/rest/spring/test/RestWithSimpleClassResponseErrorHandler.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring-test/src/main/java/org/androidannotations/rest/spring/test/RestWithSingletonBeanResponseErrorHandler.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring-test/src/test/java/org/androidannotations/rest/spring/test/RestResponseErrorHandlerTest.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring/src/main/java/org/androidannotations/rest/spring/handler/RestHandler.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring/src/main/java/org/androidannotations/rest/spring/helper/RestSpringClasses.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring/src/main/java/org/androidannotations/rest/spring/helper/RestSpringValidatorHelper.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring/src/test/java/org/androidannotations/rest/spring/AbstractResponseErrorHandler.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring/src/test/java/org/androidannotations/rest/spring/ClientWithAbstractResponseErrorHandler.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring/src/test/java/org/androidannotations/rest/spring/ClientWithNonClassResponseErrorHandler.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring/src/test/java/org/androidannotations/rest/spring/ClientWithNonResponseErrorHandler.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring/src/test/java/org/androidannotations/rest/spring/ClientWithValidResponseErrorHandler.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring/src/test/java/org/androidannotations/rest/spring/ClientWithWrongConstructorResponseErrorHandler.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring/src/test/java/org/androidannotations/rest/spring/RestResponseErrorHandlerTest.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring/src/test/java/org/androidannotations/rest/spring/ValidResponseErrorHandler.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring/src/test/java/org/androidannotations/rest/spring/WrongConstructorResponseErrorHandler.java

Add @Rest parameter to inject ResponseErrorHandler

---

AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/helper/APTCodeModelHelper.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/ExtraHandler.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/FragmentArgHandler.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/ServiceActionHandler.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/helper/IntentBuilder.java
AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/generation/ActivityWithExtras.java
AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/generation/FragmentWithArg.java
AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/generation/GenerateJavaDocTest.java
AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/generation/ServiceWithServiceAction.java

see https://github.com/excilys/androidannotations/issues/1525

copy javadoc for Activity @Extra and @FragmentArg to thier Builder

---

AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/holder/BaseGeneratedClassHolder.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/holder/SharedPrefHolder.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/SharedPrefHandler.java
AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/generation/GenerateJavaDocTest.java
AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/generation/SharedPrefWithJavaDoc.java

see https://github.com/excilys/androidannotations/issues/1551

copy @SharedPref javadoc

---

AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/holder/EComponentWithViewSupportHolder.java

Remove duplicated findViewById() calls with @SeekBarXXX

---

AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/helper/APTCodeModelHelper.java

Properly override varags methods

---

AndroidAnnotations/androidannotations-core/androidannotations-test/pom.xml
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/helper/AndroidManifestFinder.java
AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/internal/helper/AndroidManifestFinderTest.java
AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/manifest/AndroidManifestFinderTest.java
AndroidAnnotations/androidannotations-ormlite/ormlite-test/pom.xml
AndroidAnnotations/androidannotations-otto/otto-test/pom.xml
AndroidAnnotations/androidannotations-rest-spring/rest-spring-test/pom.xml
AndroidAnnotations/androidannotations-roboguice/roboguice-test/pom.xml

Use a better AndroidManifest.xml finder

---

AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/api/builder/ActivityIntentBuilder.java
AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/api/builder/ActivityStarter.java
AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/api/builder/PostActivityStarter.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/helper/ActivityIntentBuilder.java

Add withAnimations to Activity intent builder

---

AndroidAnnotations/androidannotations-rest-spring/rest-spring-test/src/main/java/org/androidannotations/rest/spring/test/MyService.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring/src/main/java/org/androidannotations/rest/spring/helper/RestAnnotationHelper.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring/src/main/java/org/androidannotations/rest/spring/helper/RestSpringClasses.java

extension/fix of PR https://github.com/excilys/androidannotations/pull/1467
related to issue https://github.com/excilys/androidannotations/issues/1440

1440 rest parameterized type reference

---

AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/helper/APTCodeModelHelper.java

Use visibility modifier from overridden method

---

AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/helper/ValidatorHelper.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring-api/src/main/java/org/androidannotations/rest/spring/annotations/Header.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring-api/src/main/java/org/androidannotations/rest/spring/annotations/Headers.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring-test/src/main/java/org/androidannotations/rest/spring/test/MyService.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring-test/src/test/java/org/androidannotations/rest/spring/test/MyServiceTest.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring/src/main/java/org/androidannotations/rest/spring/RestSpringPlugin.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring/src/main/java/org/androidannotations/rest/spring/handler/HeaderHandler.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring/src/main/java/org/androidannotations/rest/spring/handler/HeadersHandler.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring/src/main/java/org/androidannotations/rest/spring/helper/RestAnnotationHelper.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring/src/main/java/org/androidannotations/rest/spring/helper/RestSpringValidatorHelper.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring/src/test/java/org/androidannotations/rest/spring/ClientWithHeaderAndHeadersOnSameMethod.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring/src/test/java/org/androidannotations/rest/spring/ClientWithHeaderOnWrongMethod.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring/src/test/java/org/androidannotations/rest/spring/ClientWithMultipleHeaders.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring/src/test/java/org/androidannotations/rest/spring/ClientWithOneHeader.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring/src/test/java/org/androidannotations/rest/spring/ClientWithOneHeaderInHeaders.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring/src/test/java/org/androidannotations/rest/spring/RestHeadersTest.java

Refactor of #967. This is a WIP because it relies on #1448, so it cannot be merged yet. Otherwise it is done. The first interesting commit is 67249e9.

Add static headers from annotation

---

AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/helper/APTCodeModelHelper.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/holder/EActivityHolder.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/holder/EComponentWithViewSupportHolder.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/holder/EFragmentHolder.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/holder/EServiceHolder.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/holder/EViewGroupHolder.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/holder/GeneratedClassHolderDelegate.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/holder/OnActivityResultDelegate.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/holder/PreferencesDelegate.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/holder/SharedPrefHolder.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/OnActivityResultHandler.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/helper/AnnotationArrayParamExtractor.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/helper/AnnotationParamExtractor.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/helper/ViewNotifierHelper.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/rclass/RInnerClass.java
AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/generation/ContextCompatDrawableTest.java
AndroidAnnotations/pom.xml

Taking advantage of some API changes, as well fixing #1323.

Upgrade to JCodeModel 2.7.11

---

AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/annotations/OnActivityResult.java

#1580 
`@Extra` -> `@OnActivityResult.Extra`

Refining javadoc about @OnActivityResult.Extra

---

AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/annotations/Receiver.java

#1582 
`@ReceiverAction` -> `@Receiver`

Refining javadoc about @Receiver

---

AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/process/ModelProcessor.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring-api/src/main/java/org/androidannotations/rest/spring/annotations/Field.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring-api/src/main/java/org/androidannotations/rest/spring/annotations/Part.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring-api/src/main/java/org/androidannotations/rest/spring/annotations/Patch.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring/src/main/java/org/androidannotations/rest/spring/RestSpringPlugin.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring/src/main/java/org/androidannotations/rest/spring/handler/AbstractParamHandler.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring/src/main/java/org/androidannotations/rest/spring/handler/AbstractRestMethodWithParameterHandler.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring/src/main/java/org/androidannotations/rest/spring/handler/FieldHandler.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring/src/main/java/org/androidannotations/rest/spring/handler/PartHandler.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring/src/main/java/org/androidannotations/rest/spring/handler/PatchHandler.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring/src/main/java/org/androidannotations/rest/spring/handler/PostHandler.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring/src/main/java/org/androidannotations/rest/spring/handler/PutHandler.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring/src/main/java/org/androidannotations/rest/spring/helper/RestAnnotationHelper.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring/src/main/java/org/androidannotations/rest/spring/helper/RestSpringValidatorHelper.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring/src/test/java/org/androidannotations/rest/spring/ClientWithParameters.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring/src/test/java/org/androidannotations/rest/spring/RestTest.java

Implements #1333 
Some test are missing because PATCH is only available in Spring Android Rest Template 2.0

Patch for Rest

---

AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/holder/EActivityHolder.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/AfterExtrasHandler.java

see https://github.com/excilys/androidannotations/issues/1578

do not call setIntent() in onNewIntent()

---

AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/holder/BaseGeneratedClassHolder.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/Options.java
AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/generation/GenerateFinalClassesFlagTest.java

see https://github.com/excilys/androidannotations/issues/1532

1532 add option to remove final modifier from generated classes

---

AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/CorePlugin.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/ColorResHandler.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/ColorStateListResHandler.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/ContextCompatAwareResHandler.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/DrawableResHandler.java
AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/generation/ActivityWithColor.java
AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/generation/ActivityWithColorStateList.java
AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/generation/ActivityWithGetColorMethod.java
AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/generation/ActivityWithGetColorStateListMethod.java
AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/generation/ContextCompatColorStateListTest.java
AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/generation/ContextCompatColorTest.java
AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/generation/R.java
AndroidAnnotations/androidannotations-core/androidannotations/src/test/resources/org/androidannotations/generation/AndroidManifestForColor.xml
AndroidAnnotations/androidannotations-core/androidannotations/src/test/resources/org/androidannotations/generation/AndroidManifestForColorMinSdk22.xml
AndroidAnnotations/androidannotations-core/androidannotations/src/test/resources/org/androidannotations/generation/AndroidManifestForColorMinSdk23.xml
AndroidAnnotations/androidannotations-core/androidannotations/src/test/resources/org/androidannotations/generation/AndroidManifestForColorStateList.xml
AndroidAnnotations/androidannotations-core/androidannotations/src/test/resources/org/androidannotations/generation/AndroidManifestForColorStateListMinSdk22.xml
AndroidAnnotations/androidannotations-core/androidannotations/src/test/resources/org/androidannotations/generation/AndroidManifestForColorStateListMinSdk23.xml
AndroidAnnotations/androidannotations-core/androidannotations/src/test/resources/org/androidannotations/generation/ContextCompat.java

Use ContextCompat for color & ColorStateList resources.

fixes #1604

---

AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/Options.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/helper/AndroidManifestFinder.java

Add 'library' processing option

---

AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/logger/LoggerContext.java

The default value of the option was still DEBUG.

Fix default log level

---

AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/api/ViewServer.java

Update ViewServer from upstream

---

AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/annotations/sharedpreferences/DefaultStringSet.java
AndroidAnnotations/androidannotations-core/androidannotations-test/src/main/java/org/androidannotations/test/prefs/SomePrefs.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/SharedPrefHandler.java

see https://github.com/excilys/androidannotations/pull/1555#issuecomment-154579420

fix generated code for emtpy value of @DefaultStringSet

---

AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/annotations/sharedpreferences/DefaultRes.java
AndroidAnnotations/androidannotations-core/androidannotations-test/src/main/java/org/androidannotations/test/prefs/SomePrefs.java
AndroidAnnotations/androidannotations-core/androidannotations-test/src/test/java/org/androidannotations/test/prefs/PrefsActivityTest.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/SharedPrefHandler.java

see https://github.com/excilys/androidannotations/issues/1625

support string arrays in defaultres

---

AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/helper/ValidatorHelper.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring-api/src/main/java/org/androidannotations/rest/spring/annotations/Accept.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring-api/src/main/java/org/androidannotations/rest/spring/annotations/Body.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring-api/src/main/java/org/androidannotations/rest/spring/annotations/Delete.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring-api/src/main/java/org/androidannotations/rest/spring/annotations/Part.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring-api/src/main/java/org/androidannotations/rest/spring/annotations/Patch.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring-api/src/main/java/org/androidannotations/rest/spring/annotations/Post.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring-api/src/main/java/org/androidannotations/rest/spring/annotations/Put.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring-api/src/main/java/org/androidannotations/rest/spring/annotations/RestService.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring-api/src/main/java/org/androidannotations/rest/spring/annotations/SetsCookie.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring-test/src/main/java/org/androidannotations/rest/spring/test/MyService.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring-test/src/main/java/org/androidannotations/rest/spring/test/PostRestService.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring/src/main/java/org/androidannotations/rest/spring/RestSpringPlugin.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring/src/main/java/org/androidannotations/rest/spring/handler/AbstractRestMethodWithParameterHandler.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring/src/main/java/org/androidannotations/rest/spring/handler/BodyHandler.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring/src/main/java/org/androidannotations/rest/spring/handler/DeleteHandler.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring/src/main/java/org/androidannotations/rest/spring/handler/FieldHandler.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring/src/main/java/org/androidannotations/rest/spring/handler/GetHandler.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring/src/main/java/org/androidannotations/rest/spring/handler/HeadHandler.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring/src/main/java/org/androidannotations/rest/spring/handler/OptionsHandler.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring/src/main/java/org/androidannotations/rest/spring/handler/PartHandler.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring/src/main/java/org/androidannotations/rest/spring/handler/RestMethodHandler.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring/src/main/java/org/androidannotations/rest/spring/helper/RestAnnotationHelper.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring/src/main/java/org/androidannotations/rest/spring/helper/RestSpringValidatorHelper.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring/src/test/java/org/androidannotations/rest/spring/ClientWithBodyParameters.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring/src/test/java/org/androidannotations/rest/spring/ClientWithWrongBodyParameters.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring/src/test/java/org/androidannotations/rest/spring/ClientWithWrongFields.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring/src/test/java/org/androidannotations/rest/spring/ClientWithWrongRequiresCookieInUrl.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring/src/test/java/org/androidannotations/rest/spring/FieldPathParamOnSameArgument.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring/src/test/java/org/androidannotations/rest/spring/RestTest.java

see #1602
* Added `@Body` annotation
* Refactered validations for REST annotations
* Added/Fixed tests

Added @Body

---

AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/helper/ValidatorHelper.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring-test/src/main/java/org/androidannotations/rest/spring/test/MyService.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring-test/src/main/java/org/androidannotations/rest/spring/test/PathRestService.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring/src/main/java/org/androidannotations/rest/spring/helper/RestAnnotationHelper.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring/src/main/java/org/androidannotations/rest/spring/helper/RestSpringValidatorHelper.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring/src/test/java/org/androidannotations/rest/spring/ClientWithParameters.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring/src/test/java/org/androidannotations/rest/spring/ClientWithPathVariable.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring/src/test/java/org/androidannotations/rest/spring/ClientWithPostParameters.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring/src/test/java/org/androidannotations/rest/spring/RestTest.java

see #1602 and #1615 
#1615 only implementing `@Body` not replacting `@Path` placeholder function.

Remove `@Path`'s placeholder

---

AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/helper/CanonicalNameConstants.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/SystemServiceHandler.java
AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/generation/ActivityWithApplicationContextSystemServices.java
AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/generation/SystemServiceHandlerContextTest.java
AndroidAnnotations/androidannotations-core/androidannotations/src/test/resources/org/androidannotations/generation/AndroidManifestForApplicationContextSystemServices.xml

Use application context to retrieve WifiManager.

---

AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/annotations/PageScrollStateChanged.java
AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/annotations/PageScrolled.java
AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/annotations/PageSelected.java
AndroidAnnotations/androidannotations-core/androidannotations-test/src/main/java/org/androidannotations/test/PageChangeListenerActivity.java
AndroidAnnotations/androidannotations-core/androidannotations-test/src/main/res/layout/viewpagers.xml
AndroidAnnotations/androidannotations-core/androidannotations-test/src/test/java/org/androidannotations/test/PageChangeListenerActivityTest.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/handler/BaseAnnotationHandler.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/helper/CanonicalNameConstants.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/helper/ValidatorHelper.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/holder/EComponentWithViewSupportHolder.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/holder/PageChangeHolder.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/CorePlugin.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/AbstractPageChangeHandler.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/ContextCompatAwareResHandler.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/PageScrollStateChangedHandler.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/PageScrolledHandler.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/PageSelectedHandler.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/process/ProcessHolder.java
AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/android/support/v4/view/ViewPager.java
AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/generation/ActivityWithViewPager.java
AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/generation/ActivityWithViewPagerDuplicatePageScrollStateChanged.java
AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/generation/ActivityWithViewPagerDuplicatePageScrolled.java
AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/generation/ActivityWithViewPagerDuplicatePageSelected.java
AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/generation/ActivityWithViewPagerWrongParams.java
AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/generation/R.java
AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/generation/ViewPagerTest.java

Added page change

---

AndroidAnnotations/androidannotations-core/androidannotations-test/src/main/AndroidManifest.xml

Added PageChangeListenerActivity_ to remove unnecessary warning

---

AndroidAnnotations/androidannotations-otto/otto-test/pom.xml
AndroidAnnotations/androidannotations-otto/otto/pom.xml
AndroidAnnotations/androidannotations-otto/otto/src/main/java/org/androidannotations/otto/handler/AbstractOttoHandler.java
AndroidAnnotations/androidannotations-otto/otto/src/test/java/org/androidannotations/otto/EnhancedBean.java
AndroidAnnotations/androidannotations-otto/otto/src/test/java/org/androidannotations/otto/NonEnhancedBean.java
AndroidAnnotations/androidannotations-otto/otto/src/test/java/org/androidannotations/otto/OttoGenerationTest.java
AndroidAnnotations/androidannotations-otto/otto/src/test/java/org/androidannotations/otto/R.java
AndroidAnnotations/androidannotations-otto/otto/src/test/resources/org/androidannotations/otto/AndroidManifest.xml
AndroidAnnotations/androidannotations-otto/pom.xml

1657 ignore otto annotions for not enhanced classes

---

AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/NonConfigurationInstanceHandler.java
AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/ebean/EBeanTest.java
AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/ebean/SingletonBean.java

see https://github.com/excilys/androidannotations/issues/1659

1659 do not generate rebind call for singleton beans

---

AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/CorePlugin.java

see https://github.com/excilys/androidannotations/issues/1660

1660 move NonConfigurationInstanceHandler before injection handler

---

AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/annotations/IgnoreWhen.java
AndroidAnnotations/androidannotations-core/androidannotations-test/src/main/java/org/androidannotations/test/efragment/MyListFragment.java
AndroidAnnotations/androidannotations-core/androidannotations-test/src/test/java/org/androidannotations/test/efragment/MyListFragmentTest.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/holder/EFragmentHolder.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/CorePlugin.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/IgnoreWhenHandler.java

Added @IgnoreWhen

---

AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/helper/AndroidManifestFinder.java
AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/internal/helper/AndroidManifestFinderTest.java

Fix AndroidManifestFinder with Gradle Library projects

---

AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/annotations/Background.java
AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/api/BackgroundExecutor.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/BackgroundHandler.java

Fix bug with calculation of serial remaining delay

---

AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/api/BackgroundExecutor.java

fix possible deadlock in serialized background

---

AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/helper/APTCodeModelHelper.java

Fix missing varparam in super calls

---

AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/api/BackgroundExecutor.java
AndroidAnnotations/androidannotations-core/androidannotations-test/src/main/java/org/androidannotations/test/ThreadActivity.java
AndroidAnnotations/androidannotations-core/androidannotations-test/src/test/java/org/androidannotations/test/ThreadActivityTest.java

1706 remaining delay calculation

---

AndroidAnnotations/androidannotations-core/androidannotations-test/src/main/java/org/androidannotations/test/AwaitingResultActivity.java
AndroidAnnotations/androidannotations-core/androidannotations-test/src/main/java/org/androidannotations/test/ereceiver/ReceiverWithActions.java
AndroidAnnotations/androidannotations-core/androidannotations-test/src/main/java/org/androidannotations/test/receiver/ActivityWithReceiver.java
AndroidAnnotations/androidannotations-core/androidannotations-test/src/test/java/org/androidannotations/test/AwaitingResultActivityTest.java
AndroidAnnotations/androidannotations-core/androidannotations-test/src/test/java/org/androidannotations/test/ereceiver/ReceiverWithActionsTest.java
AndroidAnnotations/androidannotations-core/androidannotations-test/src/test/java/org/androidannotations/test/receiver/ActivityWithReceiverTest.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/ReceiverActionHandler.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/ReceiverHandler.java

Interpret @Extra annotated params as extras with @Receiver{Action}

---

AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/annotations/HttpsClient.java
AndroidAnnotations/androidannotations-core/androidannotations-test/src/main/java/org/androidannotations/test/SSLConnection.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/HttpsClientHandler.java

Deprecate @HttpsClient

---

AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/handler/AnnotationHandler.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/handler/BaseAnnotationHandler.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/CorePlugin.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/SupposeThreadHandler.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/TraceHandler.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/process/ModelProcessor.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/process/ModelValidator.java

updated version of https://github.com/excilys/androidannotations/pull/1755 to fix #1750

1750 fix disabling annotations

---

AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/annotations/OptionsMenuItem.java

title says everything. there was some wrong text in the javadoc.

fix OptionsMenuItem javadoc

---

AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/helper/LogHelper.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/RootContextHandler.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/TraceHandler.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/TransactionalHandler.java
AndroidAnnotations/androidannotations-ormlite/ormlite/src/main/java/org/androidannotations/ormlite/handler/OrmLiteDaoHandler.java

fixes https://github.com/excilys/androidannotations/issues/1721
successor of https://github.com/excilys/androidannotations/pull/1739

cut log tags to 23 chars

---

AndroidAnnotations/androidannotations-rest-spring/rest-spring/src/main/java/org/androidannotations/rest/spring/handler/RestMethodHandler.java

fix cookie detection when there are multiple cookies with a identical start.
see https://github.com/excilys/androidannotations/issues/1771

1771 fix cookie detection

---

AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/AbstractViewListenerHandler.java
AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/viewlistener/AbstractViewListenerActivity.java
AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/viewlistener/AdapterViewListenerActivity.java
AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/viewlistener/CompoundButtonListenerActivity.java
AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/viewlistener/TextViewListenerActivity.java
AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/viewlistener/ViewListenerCompilationTest.java
AndroidAnnotations/androidannotations-core/androidannotations/src/test/resources/org/androidannotations/viewlistener/AndroidManifest.xml

in some cases we have to cast the view used for a method call to the correct class. see https://github.com/excilys/androidannotations/issues/1767 for a sample

1767 cast views if necessary

---

AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/AbstractFragmentByHandler.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/AbstractResHandler.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/AppHandler.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/BeanHandler.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/ExtraHandler.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/FragmentArgHandler.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/HttpsClientHandler.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/InjectMenuHandler.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/OptionsMenuItemHandler.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/PrefHandler.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/PreferenceByKeyHandler.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/RootContextHandler.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/SystemServiceHandler.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/ViewByIdHandler.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/ViewsByIdHandler.java
AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/generation/ActivityWithInvalidMethodInjection.java
AndroidAnnotations/androidannotations-ormlite/ormlite/src/main/java/org/androidannotations/ormlite/handler/OrmLiteDaoHandler.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring/src/main/java/org/androidannotations/rest/spring/handler/RestServiceHandler.java

see https://github.com/excilys/androidannotations/issues/1795

Stop validation when injectHelper invalidated the annotation (#1795)

---

AndroidAnnotations/androidannotations-rest-spring/rest-spring-api/src/main/java/org/androidannotations/rest/spring/annotations/Get.java

As part of 4.0.0 you now need to include the @Path annotation.  This change updates the @Get docs to include that

Update docs to include @Path annotation

---

AndroidAnnotations/androidannotations-core/androidannotations-test/src/main/java/org/androidannotations/test/ActivityWithServices.java
AndroidAnnotations/androidannotations-core/androidannotations-test/src/test/java/org/androidannotations/test/ServiceInjectionTest.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/model/AndroidSystemServices.java

Add new system services from API 23

---

AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/annotations/ItemSelect.java

Fix ItemSelect JavaDoc

---

AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/helper/AnnotationHelper.java
AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/viewlistener/BadEditorActionViewListenerActivity.java
AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/viewlistener/ViewListenerCompilationTest.java
AndroidAnnotations/androidannotations-core/androidannotations/src/test/resources/org/androidannotations/viewlistener/AndroidManifest.xml

Fix editor action id inferring

---

AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/annotations/Receiver.java
AndroidAnnotations/androidannotations-core/androidannotations-test/src/main/AndroidManifest.xml
AndroidAnnotations/androidannotations-core/androidannotations-test/src/main/java/org/androidannotations/test/receiver/EViewAndEViewGroupWithReceiverActivity.java
AndroidAnnotations/androidannotations-core/androidannotations-test/src/main/java/org/androidannotations/test/receiver/ReceiverActions.java
AndroidAnnotations/androidannotations-core/androidannotations-test/src/main/java/org/androidannotations/test/receiver/ViewGroupWithReceiver.java
AndroidAnnotations/androidannotations-core/androidannotations-test/src/main/java/org/androidannotations/test/receiver/ViewWithReceiver.java
AndroidAnnotations/androidannotations-core/androidannotations-test/src/main/res/layout/activity_eview_eviewgroup_receiver.xml
AndroidAnnotations/androidannotations-core/androidannotations-test/src/test/java/org/androidannotations/test/receiver/EViewAndEViewGroupWithReceiverTest.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/helper/ValidatorHelper.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/holder/EServiceHolder.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/holder/EViewHolder.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/holder/ReceiverRegistrationDelegate.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/ReceiverHandler.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/helper/CoreValidatorHelper.java
AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/receiver/ReceiverRegistrationTest.java
AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/receiver/ViewWithInvalidReceiver.java
AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/receiver/ViewWithValidReceiver.java

@Receiver support for @EView and @EViewGroup

---

AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/helper/AndroidManifest.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/helper/AndroidManifestFinder.java

Reading metadata from manifest

---

AndroidAnnotations/androidannotations-core/androidannotations-test/src/main/java/org/androidannotations/test/efragment/MySupportFragment.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/ViewByIdHandler.java

Do not clear views when injected via method
see #1904

Do not clear views when injected via method

---

AndroidAnnotations/androidannotations-core/androidannotations-test/src/main/java/org/androidannotations/test/AwaitingResultActivity.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/helper/BundleHelper.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/ExtraHandler.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/ExtraParameterHandler.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/OnActivityResultHandler.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/ReceiverActionHandler.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/ReceiverHandler.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/ServiceActionHandler.java

Use `extras_.getByteArray` instad of `data.getByteArrayExtra`
\+ a little bit of cleanup
see #1898

Do not get byte array from Intent

---

AndroidAnnotations/androidannotations-core/androidannotations-test/src/main/java/org/androidannotations/test/ActivityWithServices.java
AndroidAnnotations/androidannotations-core/androidannotations-test/src/test/java/org/androidannotations/test/ServiceInjectionTest.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/model/AndroidSystemServices.java

Add ShortcutManager support to @SystemService

---

AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/holder/EViewHolder.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/holder/SharedPrefHolder.java
AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/generation/GenerateJavaDocTest.java
AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/generation/SharedPrefWithJavaDoc.java

Fix JavaDoc in generated classes

---

AndroidAnnotations/pom.xml

Update the roles of the developers listed in pom.xml

Update developers in pom.xml

---

examples/kotlin/build.gradle
examples/kotlin/gradle/wrapper/gradle-wrapper.properties
examples/kotlin/src/main/kotlin/org/androidannotations/gradle/activity/HelloAndroidActivity.kt

I updated to last eap version of kotlin, because 1.0.5-3 with kapt2 is unable to find AndroidManifest.
I added shared preferences example that is not working with kotlin.

Updated kotlin example

---

AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/helper/AndroidManifest.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/helper/AndroidManifestFinder.java

Fix AndroidManifest meta-data parsing

---

AndroidAnnotations/androidannotations-core/androidannotations-api/pom.xml
AndroidAnnotations/androidannotations-core/androidannotations-test/src/test/java/org/androidannotations/test/ThreadActivityTest.java
AndroidAnnotations/androidannotations-core/androidannotations-test/src/test/java/org/androidannotations/test/efragment/MyListFragmentTest.java
AndroidAnnotations/androidannotations-core/androidannotations-testutils/pom.xml
AndroidAnnotations/androidannotations-core/androidannotations/pom.xml
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/holder/EFragmentHolder.java
AndroidAnnotations/androidannotations-core/pom.xml
AndroidAnnotations/androidannotations-ormlite/ormlite-api/pom.xml
AndroidAnnotations/androidannotations-ormlite/ormlite/pom.xml
AndroidAnnotations/androidannotations-ormlite/pom.xml
AndroidAnnotations/androidannotations-otto/otto/pom.xml
AndroidAnnotations/androidannotations-otto/pom.xml
AndroidAnnotations/androidannotations-rest-spring/pom.xml
AndroidAnnotations/androidannotations-rest-spring/rest-spring-api/pom.xml
AndroidAnnotations/androidannotations-rest-spring/rest-spring-test/src/test/java/org/androidannotations/rest/spring/test/PathRestServiceTest.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring-test/src/test/java/org/androidannotations/rest/spring/test/PostRestServiceTest.java
AndroidAnnotations/androidannotations-rest-spring/rest-spring/pom.xml
AndroidAnnotations/androidannotations-roboguice/pom.xml
AndroidAnnotations/androidannotations-roboguice/roboguice-api/pom.xml
AndroidAnnotations/androidannotations-roboguice/roboguice/pom.xml

see https://github.com/androidannotations/androidannotations/issues/1955

Add missing copyright headers 

---

AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/api/BackgroundExecutor.java

see https://github.com/androidannotations/androidannotations/issues/1965

Use elapsedRealtime instead of currentTimeMillis

---

AndroidAnnotations/androidannotations-core/androidannotations-test/src/main/java/org/androidannotations/test/instancestate/InstanceStateView.java
AndroidAnnotations/androidannotations-core/androidannotations-test/src/test/java/org/androidannotations/test/instancestate/InstanceStateViewTest.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/holder/EActivityHolder.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/holder/EFragmentHolder.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/holder/EViewHolder.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/holder/HasInstanceState.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/holder/InstanceStateDelegate.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/holder/ViewInstanceStateDelegate.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/InstanceStateHandler.java

see https://github.com/androidannotations/androidannotations/issues/1959

Move super call onRestoreInstanceState below state restoration

---

AndroidAnnotations/androidannotations-core/androidannotations-test/src/main/java/org/androidannotations/test/ViewsInjectionOrderActivity.java
AndroidAnnotations/androidannotations-core/androidannotations-test/src/test/java/org/androidannotations/test/ViewsInjectedActivityTest.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/holder/EComponentWithViewSupportHolder.java

fix https://github.com/androidannotations/androidannotations/issues/1966

Use correct block for method injection of ViewById and ViewsById

---

.travis.yml

Fix SNAPSHOT deployment

---

AndroidAnnotations/androidannotations-core/androidannotations-test/src/main/java/org/androidannotations/test/menu/InjectMenuActivity.java
AndroidAnnotations/androidannotations-core/androidannotations-test/src/test/java/org/androidannotations/test/menu/InjectMenuActivityTest.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/holder/EActivityHolder.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/holder/EFragmentHolder.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/holder/HasOptionsMenu.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/OptionsMenuHandler.java

Fix issue reported in https://github.com/androidannotations/androidannotations/issues/1961

Inflate menu before calling method injection

---

AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/api/view/HasViews.java
AndroidAnnotations/androidannotations-core/androidannotations-test/src/test/java/org/androidannotations/test/ebean/SomeSingletonTest.java
AndroidAnnotations/androidannotations-core/androidannotations-test/src/test/java/org/androidannotations/test/efragment/MyListFragmentTest.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/holder/EActivityHolder.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/holder/EComponentWithViewSupportHolder.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/holder/EFragmentHolder.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/holder/EViewHolder.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/helper/ViewNotifierHelper.java

This PR allows to build against Android-O and fixes https://github.com/androidannotations/androidannotations/issues/2001 by adding an updated version of the view changed notfication code.

Add support for new method signature of findViewById in Android O

---

examples/kotlin/src/main/kotlin/org/androidannotations/gradle/activity/HelloAndroidActivity.kt

We got lots of issues because of this, maybe it will help users.

Add @JvmField example in Kotlin sample project

---

AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/annotations/BindingObject.java
AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/annotations/DataBound.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/helper/CanonicalNameConstants.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/holder/DataBindingDelegate.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/holder/EComponentWithViewSupportHolder.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/holder/EFragmentHolder.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/CorePlugin.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/BindingObjectHandler.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/DataBoundHandler.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/EActivityHandler.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/EFragmentHandler.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/EViewGroupHandler.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/helper/CoreValidatorHelper.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/process/ProcessHolder.java
AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/android/R.java
AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/android/databinding/ViewDataBinding.java
AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/databinding/ActivityBinding.java
AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/databinding/ActivityWithDataBoundAnnotation.java
AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/databinding/ActivityWithWrongDataBindingMethodParameters.java
AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/databinding/ActivityWithoutDataBoundAnnotation.java
AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/databinding/BeanWithDataBoundAnnotation.java
AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/databinding/DataBindingTest.java
AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/databinding/FragmentWithDataBoundAnnotation.java
AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/databinding/R.java
AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/databinding/ViewGroupWithDataBoundAnnotation.java
AndroidAnnotations/androidannotations-core/androidannotations/src/test/resources/org/androidannotations/databinding/AndroidManifest.xml
AndroidAnnotations/androidannotations-core/androidannotations/src/test/resources/org/androidannotations/databinding/DataBindingUtil.java

Add Data Binding support

---

.travis.yml
examples/gradle/build.gradle
examples/gradle/gradle/wrapper/gradle-wrapper.properties
examples/kotlin/build.gradle
examples/kotlin/gradle/wrapper/gradle-wrapper.properties

The manifest file is now found automatically, configuring it by hand
may cause issues.

Update Kotlin example

---

AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/helper/APTCodeModelHelper.java

https://github.com/androidannotations/androidannotations/issues/2041

Fix copying non-AA array of annotations

---

AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/holder/EViewHolder.java

Fix invoking wrong super method from onDetachedFromWindow

---

AndroidAnnotations/androidannotations-rest-spring/rest-spring-api/src/main/java/org/androidannotations/rest/spring/annotations/Rest.java

Clarify @Rest Javadoc

---

AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/helper/APTCodeModelHelper.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/generation/ResourceCodeWriter.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/generation/SourceCodeWriter.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/process/ProcessHolder.java
AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/databinding/DataBindingTest.java
AndroidAnnotations/pom.xml

 Do not import the android.R class

---

AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/helper/InjectHelper.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/InstanceStateHandler.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/NonConfigurationInstanceHandler.java

Validate injected field to be non-final

---

AndroidAnnotations/androidannotations-rest-spring/rest-spring/src/main/java/org/androidannotations/rest/spring/helper/RestSpringValidatorHelper.java

Use correct parameter order to fix converter validation

---

AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/process/ModelProcessor.java
AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/generation/InvalidFragmentWithValidBean.java
AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/generation/NestedEnhancedClassGenerationTest.java

This fixes the infinite loop mentioned in #2143

Fix infinite loop when enclosing class is invalid

---

AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/helper/CanonicalNameConstants.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/helper/ValidatorHelper.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/holder/DataBindingDelegate.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/holder/EActivityHolder.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/holder/EComponentWithViewSupportHolder.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/holder/EFragmentHolder.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/holder/HasPreferences.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/holder/PreferencesDelegate.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/AbstractPageChangeHandler.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/BindingObjectHandler.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/ContextCompatAwareResHandler.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/PageScrollStateChangedHandler.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/PageScrolledHandler.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/PageSelectedHandler.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/PreferenceChangeHandler.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/PreferenceClickHandler.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/ReceiverHandler.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/WindowFeatureHandler.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/helper/ActivityIntentBuilder.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/helper/CoreValidatorHelper.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/process/ProcessHolder.java

Do NOT merge yet. Needs to be rebased after my other recent PRs have been merged as this contains thíer changes too.
The intention is to add support for new AndroidX classes in addition to support library. 
Checklist of classes I consider done.
@WonderCsabo If you want to support me, feel free to create tests for classes I have checked. ;)

Add support for AndroidX classes

---

AndroidAnnotations/.idea/checkstyle-idea.xml
AndroidAnnotations/pom.xml

I forgot to update Checkstyle version in the IDE. It is really a shame that we have to define things in two places, but i know this is helping importing the project.

Update Checkstyle version in IDEA config

---

AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/ebean/EBeanTest.java
AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/ebean/SomeActivity.java
AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/ebean/SomeBeanWithContextAndNoParamsConstructors.java
AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/ebean/SomeBeanWithContextParamConstructor.java
AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/ebean/SomeBeanWithEmptyConstructor.java
AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/ebean/SomeBeanWithNonContextConstructors.java

This PR adds some extra tests to EBean tests, specially related with the constructors.

Increase coverage of EBean Tests.

---

AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/annotations/RootFragment.java
AndroidAnnotations/androidannotations-core/androidannotations-test/src/main/AndroidManifest.xml
AndroidAnnotations/androidannotations-core/androidannotations-test/src/main/java/org/androidannotations/test/ebean/ActivityWithBeansWithRootFragment.java
AndroidAnnotations/androidannotations-core/androidannotations-test/src/main/java/org/androidannotations/test/ebean/CustomFragment.java
AndroidAnnotations/androidannotations-core/androidannotations-test/src/main/java/org/androidannotations/test/ebean/DifferentFragment.java
AndroidAnnotations/androidannotations-core/androidannotations-test/src/main/java/org/androidannotations/test/ebean/SomeBeanWithRootFragment.java
AndroidAnnotations/androidannotations-core/androidannotations-test/src/main/java/org/androidannotations/test/ebean/SomeBeanWithRootFragmentWithCustomFragment.java
AndroidAnnotations/androidannotations-core/androidannotations-test/src/main/java/org/androidannotations/test/ebean/SomeBeanWithRootFragmentWithDifferentFragment.java
AndroidAnnotations/androidannotations-core/androidannotations-test/src/test/java/org/androidannotations/test/ebean/RootFragmentTest.java
AndroidAnnotations/androidannotations-core/androidannotations-testutils/src/main/java/org/androidannotations/testutils/AAProcessorTestHelper.java
AndroidAnnotations/androidannotations-core/androidannotations-testutils/src/main/java/org/androidannotations/testutils/ProcessorTestHelper.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/holder/EBeanHolder.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/holder/EComponentHolder.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/holder/EFragmentHolder.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/CorePlugin.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/BeanHandler.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/EBeanHandler.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/RootFragmentHandler.java
AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/ebean/CustomFragment.java
AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/ebean/RootFragmentTest.java
AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/ebean/SomeBeanWithRootFragment.java
AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/ebean/SomeBeanWithRootFragmentWithCustomFragment.java
AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/ebean/SomeBeanWithRootFragmentWithObject.java
AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/ebean/SomeBeanWithRootFragmentWithPrivateField.java
AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/ebean/SomeBeanWithRootFragmentWithSomeInterface.java
AndroidAnnotations/androidannotations-core/androidannotations/src/test/resources/org/androidannotations/ebean/CustomSupportFragment.java
AndroidAnnotations/androidannotations-core/androidannotations/src/test/resources/org/androidannotations/ebean/SomeBeanWithRootFragmentWithCustomSupportFragment.java
AndroidAnnotations/androidannotations-core/androidannotations/src/test/resources/org/androidannotations/ebean/SomeBeanWithRootFragmentWithSupportFragment.java
AndroidAnnotations/androidannotations-core/androidannotations/src/test/resources/org/androidannotations/ebean/support/Fragment.java

I've implemented the support for a `@RootFragment` which solves the issue #1636 . Please let me know about any question/suggestion regarding the solution. 
Thanks.

Implements @RootFragment annotation support.

---

AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/AndroidAnnotationsEnvironment.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/handler/BaseAnnotationHandler.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/helper/ClassesHolder.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/holder/BaseGeneratedClassHolder.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/holder/EServiceHolder.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/holder/FoundHolder.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/holder/GeneratedClassHolderDelegate.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/InternalAndroidAnnotationsEnvironment.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/HttpsClientHandler.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/helper/IntentBuilder.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/process/ModelProcessor.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/process/ProcessHolder.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/plugin/PluginClassHolder.java

Add methods to PluginClassHolder to facilitate the work with Plugins. Also included a little check in EServiceHoldr to ensure `getStartLifecycleAfterSuperBlock doesn't return NULL (similar to how it works in other places).

Add useful methods to PluginClassHolder

---

AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/AndroidAnnotationProcessor.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/Options.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/helper/FileHelper.java
AndroidAnnotations/androidannotations-core/androidannotations/src/main/resources/META-INF/gradle/incremental.annotation.processors

https://github.com/androidannotations/androidannotations/issues/2193

Support incremental annotation processing

---

AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/helper/FileHelper.java

https://github.com/androidannotations/androidannotations/issues/2267

Fix finding project folder on Windows
