examples/HelloWorldEclipse/.classpath
The `libs` directory added as entry of src in .classpath will cause `Multiple dex files define` error, such as `Multiple dex files define Lorg/androidannotations/annotations/AfterExtras;`.  
The concrete reason is the Eclipse will copy `jar` file in the `libs` directory to the `bin/classes` directory, such as follows:
F:\workspace\HelloWorldEclipse\bin>tree /F
│  androidannotations.log
│  AndroidManifest.xml
│  R.txt
│  resources.ap_
│
├─classes
│  │  androidannotations-api-3.1.jar
│  │
│  ├─android
│  │  └─support
│  │      └─v7
│  └─org
│      └─androidannotations
├─dexedLibs
│      android-support-v4-259169c26135dabc8292fb369fe13d18.jar
│      android-support-v7-appcompat-fe8356d7d51ca5e59edf416a1b47d8dc.jar
│      androidannotations-api-3.1-4d54da3f520ba51cf94de9910532a000.jar
│ …
=> delete libs directory as an entry in src to deal with the Multiple dex files error.

AndroidAnnotations/androidannotations-api/src/main/java/org/androidannotations/api/builder/ActivityIntentBuilder.java, AndroidAnnotations/androidannotations-api/src/main/java/org/androidannotations/api/builder/ActivityStarter.java, AndroidAnnotations/androidannotations-api/src/main/java/org/androidannotations/api/builder/Builder.java, AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/helper/ActivityIntentBuilder.java, AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/helper/CanonicalNameConstants.java, AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/process/ProcessHolder.java, AndroidAnnotations/androidannotations/src/test/java/org/androidannotations/generation/ActivityIntentFragmentTest.java, AndroidAnnotations/androidannotations/src/test/resources/org/androidannotations/generation/ActivityCompat.java, AndroidAnnotations/androidannotations/src/test/resources/org/androidannotations/generation/support/ActivityCompat.java
=> Activity Intent builder with options

AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/handler/BaseGeneratingAnnotationHandler.java, AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/helper/ValidatorHelper.java, AndroidAnnotations/androidannotations/src/test/java/org/androidannotations/innerclasses/AbstractActivityWithAbstractInnerClass.java, AndroidAnnotations/androidannotations/src/test/java/org/androidannotations/innerclasses/AbstractActivityWithNonAbstractInnerClass.java, AndroidAnnotations/androidannotations/src/test/java/org/androidannotations/innerclasses/InnerClassTest.java, AndroidAnnotations/androidannotations/src/test/resources/org/androidannotations/innerclasses/AndroidManifest.xml
=> Invalidate non-abstract inner classes with abstract outer class

AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/AndroidAnnotationProcessor.java, AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/handler/AppHandler.java, AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/handler/NonConfigurationInstanceHandler.java, AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/handler/ReceiverHandler.java, AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/handler/RoboGuiceHandler.java, AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/handler/rest/RestServiceHandler.java, AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/helper/APTCodeModelHelper.java, AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/helper/ActivityIntentBuilder.java, AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/helper/AndroidManifestFinder.java, AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/helper/AnnotationHelper.java, AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/helper/IntentBuilder.java, AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/helper/ModelConstants.java, AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/helper/OptionsHelper.java, AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/helper/ValidatorHelper.java, AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/helper/ViewNotifierHelper.java, AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/holder/BaseGeneratedClassHolder.java, AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/holder/EActivityHolder.java, AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/holder/EApplicationHolder.java, AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/holder/EBeanHolder.java, AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/holder/EComponentHolder.java, AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/holder/EFragmentHolder.java, AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/holder/EProviderHolder.java, AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/holder/EReceiverHolder.java, AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/holder/EServiceHolder.java, AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/holder/EViewHolder.java, AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/holder/InstanceStateHolder.java, AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/holder/ReceiverRegistrationHolder.java, AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/holder/SharedPrefHolder.java, AndroidAnnotations/androidannotations/src/test/java/org/androidannotations/generation/ChangedGenerationSuffixTest.java, AndroidAnnotations/androidannotations/src/test/java/org/androidannotations/utils/AAProcessorTestHelper.java
see https://github.com/excilys/androidannotations/issues/1209
this allows to set the `generationSuffix` via options. at the moment the same valule is used for all generated stuff (classes, fields, methods) where it before was `_`. But for a first look i already opened the PR.
=> add option to change GENERATION_SUFFIX

AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/handler/AbstractListenerHandler.java, AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/handler/BackgroundHandler.java, AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/handler/BaseAnnotationHandler.java, AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/handler/ExtraHandler.java, AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/handler/ExtraParameterHandler.java, AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/handler/FragmentArgHandler.java, AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/handler/IgnoredWhenDetachedHandler.java, AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/handler/InstanceStateHandler.java, AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/handler/ItemClickHandler.java, AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/handler/ItemLongClickHandler.java, AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/handler/NonConfigurationInstanceHandler.java, AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/handler/OrmLiteDaoHandler.java, AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/handler/PreferenceChangeHandler.java, AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/handler/ProduceHandler.java, AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/handler/ReceiverActionHandler.java, AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/handler/ReceiverHandler.java, AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/handler/RoboGuiceHandler.java, AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/handler/ServiceActionHandler.java, AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/handler/SubscribeHandler.java, AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/handler/SupposeBackgroundHandler.java, AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/handler/SupposeUiThreadHandler.java, AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/handler/TraceHandler.java, AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/handler/TransactionalHandler.java, AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/handler/UiThreadHandler.java, AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/handler/ViewByIdHandler.java, AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/handler/ViewsByIdHandler.java, AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/handler/WakeLockHandler.java, AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/handler/rest/RestHandler.java, AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/handler/rest/RestMethodHandler.java, AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/holder/EComponentWithViewSupportHolder.java
Implements #1442. The `AnnotationHelper` usages cannot be easily refactored, since different handlers use different subclasses of it.
=> Refactor APTCodeModelHelper usages

AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/helper/BundleHelper.java, AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/helper/ValidatorHelper.java, AndroidAnnotations/functional-test-1-5/src/main/java/org/androidannotations/test15/GenericFragmentArguments.java, AndroidAnnotations/functional-test-1-5/src/test/java/org/androidannotations/test15/GenericFragmentArgsTest.java
Related to #1444.
The old code has lots of things like this:
```java
DeclaredType declaredType = (DeclaredType) element;
typeString = declaredType.asElement().toString();
elementType = annotationHelper.typeElementFromQualifiedName(typeString);
```
So basically serialize the type to a string, the reload the type from it. It is totally unnecessary in most cases i think, but it is maybe an old workaround that i do not know. All tests pass and my projects are working with the new way. @DayS @yDelouis any thoughts whether the old method was intentional or not?
=> Support @FragmentArg on fields with type variable type

AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/annotations/EBean.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/helper/ValidatorHelper.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/EBeanHandler.java, AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/ebean/EBeanTest.java, AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/ebean/InterfaceWithEBean.java
=> @EBean validation error on interface

AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/annotations/KeyDown.java, AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/annotations/KeyLongPress.java, AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/annotations/KeyMultiple.java, AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/annotations/KeyUp.java, AndroidAnnotations/androidannotations-core/androidannotations-test/src/main/AndroidManifest.xml, AndroidAnnotations/androidannotations-core/androidannotations-test/src/main/java/org/androidannotations/test/keyevents/KeyEventsActivity.java, AndroidAnnotations/androidannotations-core/androidannotations-test/src/test/java/org/androidannotations/test/keyevents/KeyEventsActivityTest.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/helper/CanonicalNameConstants.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/helper/KeyCodeHelper.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/holder/EComponentWithViewSupportHolder.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/holder/HasKeyEventCallbackMethods.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/holder/KeyEventCallbackMethodsDelegate.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/CorePlugin.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/AbstractKeyEventHandler.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/KeyDownHandler.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/KeyLongPressHandler.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/KeyMultipleHandler.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/KeyUpHandler.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/helper/CoreValidatorHelper.java, AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/keyevents/ActivityWithKeyEvents.java, AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/keyevents/ActivityWithKeyEventsWithNotUniqueKeycode.java, AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/keyevents/ActivityWithKeyEventsWithWrongParameter.java, AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/keyevents/FragmentWithKeyEvents.java, AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/keyevents/KeyEventTest.java, AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/keyevents/R.java, AndroidAnnotations/androidannotations-core/androidannotations/src/test/resources/org/androidannotations/keyevents/AndroidManifest.xml
=> Annotations to handle key events

AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/annotations/sharedpreferences/DefaultStringSet.java, AndroidAnnotations/androidannotations-core/androidannotations-test/src/main/java/org/androidannotations/test/prefs/SomePrefs.java, AndroidAnnotations/androidannotations-core/androidannotations-test/src/test/java/org/androidannotations/test/prefs/PrefsActivityTest.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/SharedPrefHandler.java
based on https://github.com/excilys/androidannotations/pull/1553
This PR allows to provide a default value for a `@DefaultStringSet` annotated method in a `@SharedPref` interface.
Usage:
```java
@DefaultStringSet({"a", "b", "c"})
Set<String> setWithDefault();
```
That generates:
```java
public StringSetPrefField setWithDefault() {
return stringSetField("setWithDefault", new HashSet<String>(Arrays.asList("a", "b", "c")));
}
```
=> Allow to provide a default value for @DefaultStringSet

AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/helper/ValidatorHelper.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/ExtraParameterHandler.java, AndroidAnnotations/androidannotations-rest-spring/rest-spring-api/src/main/java/org/androidannotations/rest/spring/annotations/Field.java, AndroidAnnotations/androidannotations-rest-spring/rest-spring-api/src/main/java/org/androidannotations/rest/spring/annotations/Part.java, AndroidAnnotations/androidannotations-rest-spring/rest-spring-api/src/main/java/org/androidannotations/rest/spring/annotations/Path.java, AndroidAnnotations/androidannotations-rest-spring/rest-spring-test/src/main/java/org/androidannotations/rest/spring/test/MyService.java, AndroidAnnotations/androidannotations-rest-spring/rest-spring-test/src/main/java/org/androidannotations/rest/spring/test/PathRestService.java, AndroidAnnotations/androidannotations-rest-spring/rest-spring-test/src/main/java/org/androidannotations/rest/spring/test/PostRestService.java, AndroidAnnotations/androidannotations-rest-spring/rest-spring-test/src/test/java/org/androidannotations/rest/spring/test/MyServiceTest.java, AndroidAnnotations/androidannotations-rest-spring/rest-spring-test/src/test/java/org/androidannotations/rest/spring/test/PathRestServiceTest.java, AndroidAnnotations/androidannotations-rest-spring/rest-spring-test/src/test/java/org/androidannotations/rest/spring/test/PostRestServiceTest.java, AndroidAnnotations/androidannotations-rest-spring/rest-spring-test/src/test/java/org/androidannotations/rest/spring/test/RequestTestBuilder.java, AndroidAnnotations/androidannotations-rest-spring/rest-spring/src/main/java/org/androidannotations/rest/spring/RestSpringPlugin.java, AndroidAnnotations/androidannotations-rest-spring/rest-spring/src/main/java/org/androidannotations/rest/spring/handler/PathHandler.java, AndroidAnnotations/androidannotations-rest-spring/rest-spring/src/main/java/org/androidannotations/rest/spring/handler/PostHandler.java, AndroidAnnotations/androidannotations-rest-spring/rest-spring/src/main/java/org/androidannotations/rest/spring/helper/RestAnnotationHelper.java, AndroidAnnotations/androidannotations-rest-spring/rest-spring/src/main/java/org/androidannotations/rest/spring/helper/RestSpringClasses.java, AndroidAnnotations/androidannotations-rest-spring/rest-spring/src/main/java/org/androidannotations/rest/spring/helper/RestSpringValidatorHelper.java, AndroidAnnotations/androidannotations-rest-spring/rest-spring/src/test/java/org/androidannotations/rest/spring/ClientWithMissingFormConverter.java, AndroidAnnotations/androidannotations-rest-spring/rest-spring/src/test/java/org/androidannotations/rest/spring/ClientWithPathVariable.java, AndroidAnnotations/androidannotations-rest-spring/rest-spring/src/test/java/org/androidannotations/rest/spring/ClientWithPostParameters.java, AndroidAnnotations/androidannotations-rest-spring/rest-spring/src/test/java/org/androidannotations/rest/spring/ClientWithWrongFields.java, AndroidAnnotations/androidannotations-rest-spring/rest-spring/src/test/java/org/androidannotations/rest/spring/ClientWithWrongPathVariables.java, AndroidAnnotations/androidannotations-rest-spring/rest-spring/src/test/java/org/androidannotations/rest/spring/FieldPathParamOnSameArgument.java, AndroidAnnotations/androidannotations-rest-spring/rest-spring/src/test/java/org/androidannotations/rest/spring/RestTest.java
`@PathParam`: allows to add different url variable name than the method parameter name. It can be expanded later to use url encoding.
```java
@Post("/login{id}")
void login(User user, @Path("id") String identifier);
```
`@Field`: allows to add post parameters as method parameters, just like url variables. Form data and multipart data are supported.
```java
@Post("/login")
void login(@Field String username, @Field String password);
```
About multipart: currently, it requires some boilerplate, but much less than before:
```java
@Post("/profilepicture")
@RequiresHeader("Content-Type")
void upload(@Field String name, @Field FileResource picture);
userRestClient.setHeader("Content-Type", MULTIPART_FORM_DATA);
// normal calls
```
It would be better to remove the need for this.
* we could use …
=> Add @Field, @Part and @Path

AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/annotations/FragmentById.java, AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/annotations/FragmentByTag.java, AndroidAnnotations/androidannotations-core/androidannotations-testutils/src/main/java/org/androidannotations/testutils/ProcessorTestHelper.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/AbstractFragmentByHandler.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/FragmentByIdHandler.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/FragmentByTagHandler.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/helper/CoreValidatorHelper.java, AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/generation/ActivityWithChildFragment.java, AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/generation/FragmentByChildFragmentManagerTest.java, AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/generation/NativeFragmentWithChild.java, AndroidAnnotations/androidannotations-core/androidannotations/src/test/resources/org/androidannotations/generation/SupportFragmentWithChild.java, AndroidAnnotations/androidannotations-core/androidannotations/src/test/resources/org/androidannotations/generation/support/Fragment.java, AndroidAnnotations/androidannotations-core/androidannotations/src/test/resources/org/androidannotations/generation/support/old/Fragment.java
Implements #1302.
This is a breaking change, because `@EFragment`s now always use `getFragmentManager()` instead of `getActivity().getFragmentManager()` (or `getChildFragmentManager()` but only if that is set).
=> @FragmentByXXX inject child Fragments

AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/annotations/Extra.java, AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/annotations/FragmentArg.java, AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/annotations/InstanceState.java, AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/annotations/OnActivityResult.java, AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/annotations/Receiver.java, AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/annotations/ReceiverAction.java, AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/annotations/ServiceAction.java, AndroidAnnotations/androidannotations-core/androidannotations-test/pom.xml, AndroidAnnotations/androidannotations-core/androidannotations-test/src/main/java/org/androidannotations/test/ExtraInjectedActivity.java, AndroidAnnotations/androidannotations-core/androidannotations-test/src/main/java/org/androidannotations/test/instancestate/SaveInstanceStateActivity.java, AndroidAnnotations/androidannotations-core/androidannotations-test/src/main/java/org/androidannotations/test/parceler/ParcelerBean.java, AndroidAnnotations/androidannotations-core/androidannotations-test/src/test/java/org/androidannotations/test/InjectExtraTest.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/helper/AnnotationHelper.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/helper/BundleHelper.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/helper/CanonicalNameConstants.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/helper/ParcelerHelper.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/helper/ValidatorHelper.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/FragmentArgHandler.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/InstanceStateHandler.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/helper/IntentBuilder.java
This PR offers [Parceler](http://parceler.org) integration which wraps and unwraps beans annotated with `@Parcel` transparently when they are used in `@Extra` or `@InstanceState` aspects.  This is a rework of this previous PR: #977
=> Added parceler `@Extra` and `@InstanceState` support

AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/model/AnnotationElementsHolder.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/model/ModelExtractor.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/process/ModelValidator.java, AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/menu/OptionsMenuItemSubActivity.java, AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/menu/OptionsMenuItemSubSubActivity.java, AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/menu/OptionsMenuItemSubSubSubActivity.java, AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/menu/OptionsMenuItemTest.java, AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/menu/R.java
=> Fixed a problem with travasing ancestors.

AndroidAnnotations/androidannotations-core/androidannotations/pom.xml, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/helper/CanonicalNameConstants.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/helper/ValidatorParameterHelper.java, AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/helper/ValidatorParameterHelperTest.java
#1561
(In case @yDelouis or @dodgex can finishing up, I will close this pull request.)
#1443
* Rebase the test case commit 096b087 since it fail travis ci.
* From this [comments](https://github.com/excilys/androidannotations/pull/1561#issuecomment-141810917), finishing up [ValidatorParameterHelper#getWrapperType()](https://github.com/yDelouis/androidannotations/blob/1443_fixInOrderParamValidation/AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/helper/ValidatorParameterHelper.java#L402)
* Finished up [ValidatorParameterHelper#getWrapperType()](https://github.com/yDelouis/androidannotations/blob/1443_fixInOrderParamValidation/AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/helper/ValidatorPa …
=> Fix in order parameter validation 2

AndroidAnnotations/androidannotations-rest-spring/rest-spring/src/main/java/org/androidannotations/rest/spring/helper/RestSpringValidatorHelper.java, AndroidAnnotations/androidannotations-rest-spring/rest-spring/src/test/java/org/androidannotations/rest/spring/ClientWithPatch.java, AndroidAnnotations/androidannotations-rest-spring/rest-spring/src/test/java/org/androidannotations/rest/spring/RestTest.java
Follow-up for #1587.
We should have tests for Spring 2. The most coverage would be if we create a new test project which uses Spring 2. Or we can just change the the version for 2, but that means we do not test important things which are differently generated in Spring 1.
=> Fix @Patch validation

AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/annotations/UiThread.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/UiThreadHandler.java
add javadoc note to `UiThread#propagation()` that it is ignored for non-zero delay values and add a warning to the validation.
see https://github.com/excilys/androidannotations/issues/1612
=> 1612 warn when propagation reuse is used with delay

AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/holder/EActivityHolder.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/holder/EComponentHolder.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/holder/EComponentWithViewSupportHolder.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/holder/EFragmentHolder.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/holder/EServiceHolder.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/holder/HasPreferences.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/holder/PreferencesDelegate.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/CorePlugin.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/AbstractFragmentByHandler.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/AbstractResHandler.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/AfterInjectHandler.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/AfterPreferencesHandler.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/AfterViewsHandler.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/AppHandler.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/BeanHandler.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/CustomTitleHandler.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/FromHtmlHandler.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/FullscreenHandler.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/HierarchyViewerSupportHandler.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/HttpsClientHandler.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/PrefHandler.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/RootContextHandler.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/SystemServiceHandler.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/ViewsByIdHandler.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/WindowFeatureHandler.java, AndroidAnnotations/androidannotations-ormlite/ormlite/src/main/java/org/androidannotations/ormlite/handler/OrmLiteDaoHandler.java, AndroidAnnotations/androidannotations-ormlite/ormlite/src/main/java/org/androidannotations/ormlite/holder/OrmLiteHolder.java, AndroidAnnotations/androidannotations-rest-spring/rest-spring/src/main/java/org/androidannotations/rest/spring/handler/RestServiceHandler.java, AndroidAnnotations/pom.xml
Related to #1466.
This is incomplete. For some reasons, it generates the following:
```java
private void init_(Bundle savedInstanceState) {
{
Resources resources_ = this.getResources();
injected_string = resources_.getString(R.string.injected_string);
injectedString = resources_.getString(R.string.injected_string);
helloHtml = Html.fromHtml(resources_.getString(R.string.hello_html));
htmlInjected = Html.fromHtml(resources_.getString(R.string.hello_html));
}
}
```
Note the extra block with braces and indent. I could not figure out why is this happening. Any help is much appreciated.
=> Create blocks for injection and after injection

AndroidAnnotations/androidannotations-core/androidannotations-test/src/main/java/org/androidannotations/test/instancestate/SaveInstanceStateActivity.java, AndroidAnnotations/androidannotations-core/androidannotations-test/src/test/java/org/androidannotations/test/instancestate/SaveInstanceStateActivityParameterizedTest.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/helper/BundleHelper.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/helper/ValidatorHelper.java, AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/helper/BundleSparseArrayActivityTest.java, AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/helper/BundleSparseArrayCompileSuccessActivity.java, AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/helper/BundleSparseArrayNoGenericsTypeActivity.java, AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/helper/BundleSparseArrayNoParcelableTypeActivity.java, AndroidAnnotations/androidannotations-core/androidannotations/src/test/resources/org/androidannotations/helper/AndroidManifest.xml
=> Support new type in bundles

AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/ContextCompatAwareResHandler.java, AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/generation/ContextCompatColorTest.java, AndroidAnnotations/androidannotations-core/androidannotations/src/test/resources/org/androidannotations/generation/support/old/ContextCompat.java
=> Do not use ContextCompat if target method is not available

AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/helper/CanonicalNameConstants.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/helper/AndroidManifestFinder.java, AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/manifest/InstantRunManifestTest.java, AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/manifest/MyApplication.java, AndroidAnnotations/androidannotations-core/androidannotations/src/test/resources/org/androidannotations/manifest/CorrectInstantRunManifest.xml, AndroidAnnotations/androidannotations-core/androidannotations/src/test/resources/org/androidannotations/manifest/IncorrectInstantRunManifest.xml
Instant Run swaps the application class name in the manifest to its own
bootstrap application, which can instrument the app to use instant Run.
It also adds a new "name" attribute to the manifest, which contains the
original application. When Instant Run is used, we should retrieve this
attribute as the application class name.
Related to #1697.
=> Support Instant Run application class

AndroidAnnotations/androidannotations-core/androidannotations-test/src/main/java/org/androidannotations/test/instancestate/InstanceStateAfterInjectActivity.java, AndroidAnnotations/androidannotations-core/androidannotations-test/src/test/java/org/androidannotations/test/instancestate/InstanceStateAfterInjectActivityTest.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/holder/InstanceStateDelegate.java
In some scenarios, state restoration was called after `@AfterInject`
methods are called. This commit fixes this issue by moving the restore
call to the dedicated injection block.
Fixes #1703.
=> Fix @InstanceState calling order

examples/kotlin/src/main/kotlin/org/androidannotations/gradle/activity/HelloAndroidActivity.kt
In Kotlin, the default visibility (no modifier) is public.
There is no equivalent modifier of package-private, so we must use protected.
=> Make members in Kotlin example protected

AndroidAnnotations/androidannotations-rest-spring/rest-spring/src/main/java/org/androidannotations/rest/spring/helper/RestAnnotationHelper.java
Implements #1735 
Some test are missing because ParameterizedTypeReference is only available in Spring Android Rest Template 2.0.
I tested it locally.
=> Fixes RestTemplate generation with ResponseEntity as return type

AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/api/BackgroundExecutor.java, AndroidAnnotations/androidannotations-core/androidannotations-test/src/test/java/org/androidannotations/test/ThreadActivityTest.java
Revert the commit provided to fix the issue https://github.com/excilys/androidannotations/issues/1689 because it broke the serial execution of background tasks. This fixes #1775.
Then provide another commit, that fixes #1689.
See commit messages for details.
=> Fix @Background serial execution

AndroidAnnotations/androidannotations-rest-spring/rest-spring-api/src/main/java/org/androidannotations/rest/spring/annotations/Post.java
As part of 4.0.0 all rest method params now need annotations.  This adds the @Path annotation to the docs for @Post
=> Update docs to include @Path annotation

AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/holder/EComponentHolder.java
This PR should fix https://github.com/excilys/androidannotations/issues/1847 by always setting the resourcesRef (`resoruces_`) before trying to inject the resources itself.
=> 1847 fix method injection for resources

.travis.yml, AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/api/bundle/BundleHelper.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/helper/ErrorHelper.java, AndroidAnnotations/androidannotations-roboguice/roboguice-api/src/main/java/org/androidannotations/roboguice/annotations/RoboGuice.java, AndroidAnnotations/pom.xml, CONTRIBUTING.md, README.md
As we have moved form github.com/excilys to github.com/androidannotations this PR aims to update all related references in the codebase
=> Update github links to reflect the new organization

AndroidAnnotations/pom.xml, AndroidAnnotations/src/etc/header_both.txt, AndroidAnnotations/src/etc/header_new.txt
This does the following:
* `maven license:check` passes for all combinations
* `maven license:format` will add the license with only AA project as copyright holder (this should be fine, as mostly new files are formatted for license headers, existing files already have a header. New files should only have the AA project in the header).
* Adding the AA line to the header for changed files is still not enforced by the plugin, it must be enforced manually when reviewing PRs 😢
=> Update licenses for new ownership

AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/holder/SharedPrefHolder.java, AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/generation/GenerateJavaDocTest.java, AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/generation/SharedPrefWithJavaDoc.java
```
Previously, "<p><b>Defaults to</b>: </p>" was generated for string fields with
an empty default value. This commit inserts back-ticks so that the default
value in the javadoc is easier to be identified:
* "<p><b>Defaults to</b>: ""</p>" for empty default strings
* "<p><b>Defaults to</b>: "value"</p>" for @DefaultString("value")
```
I had to wrap this in code tags because the b-tags made the message unreadable
=> Clarified javadocs in @SharedPrefs with backticks

AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/TraceHandler.java
- prefix variables with trace
- postifx variables with underscore
see #1891
=> Rename variables used for @Trace to avoid name collisions

AndroidAnnotations/androidannotations-core/androidannotations-test/src/main/java/org/androidannotations/test/eview/ViewWithInstanceState.java, AndroidAnnotations/androidannotations-core/androidannotations-test/src/main/java/org/androidannotations/test/instancestate/MyParcelableBean.java, AndroidAnnotations/androidannotations-core/androidannotations-test/src/test/java/org/androidannotations/test/eview/ViewInstanceStateTest.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/helper/ValidatorHelper.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/holder/EViewHolder.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/holder/ViewInstanceStateDelegate.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/InstanceStateHandler.java
This PR is based on the [work](https://github.com/simopete/androidannotations/commit/67b55ac1b6592e7326e0ef4a16a786d42c4f9fdb) of @simopete. 
Adding support of `@InstanceState` to custom views.
- Update copyright header
- Added a test case
=> Support instance state for views

AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/annotations/sharedpreferences/SharedPref.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/SharedPrefHandler.java, AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/sharedprefs/ActivityInManifest.java, AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/sharedprefs/PrefsCollection.java, AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/sharedprefs/PrefsCollectionWithError.java, AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/sharedprefs/SharedPrefNamingTest.java, AndroidAnnotations/androidannotations-core/androidannotations/src/test/resources/org/androidannotations/sharedprefs/AndroidManifest.xml
This PR implements the feature request of https://github.com/androidannotations/androidannotations/issues/1675.
With this PR it is possible to provide a custom name for the preference file of a `@SharedPref` interface.
=> Add name parameter to @SharedPref

AndroidAnnotations/androidannotations-core/androidannotations-test/src/test/java/org/androidannotations/test/efragment/MyListFragmentTest.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/holder/EFragmentHolder.java
This avoids methods annotated with @IgnoreWhen(IgnoreWhen.State.VIEW_DESTROYED) to be called before the fragment has been created/recreated.
This PR fixes the feature request of #1942
=> Default viewDestroyed_ to true

AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/helper/AndroidManifestFinder.java, AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/internal/helper/AndroidManifestFinderTest.java
The new Android Gradle Plugin changed the location of the generated
manifest for library projects. This commit adds the ability to find
the manifest in the new location.
#1974
=> Fix lib manifest finding with Gradle plugin 2.3

.travis.yml
see https://github.com/androidannotations/androidannotations/issues/1979
With the removal of JDK7 from travis build SNAPSHOTS where no longer deployed as they where configured to run in the JDK7 build
=> Trigger SNAPSHOT deployment for JDK8 builds

AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/helper/AndroidManifestFinder.java, AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/internal/helper/AndroidManifestFinderTest.java
This PR allows the AndroidManifestFinder to find manifests for gradle builds with kotlin-only and android build plugin `3.0.0-alpha1`.
```
:app:kaptDebugKotlin
e: error: Could not find the AndroidManifest.xml file, using  generation folder [D:\***\app\build\generated\source\kapt\debug])
```
=> Fix android manifest finder

AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/holder/EIntentServiceHolder.java
This PR avoids potential NullPointerExceptions in IntentServices as `onHandleIntent` might be called with a null intent.
see #1499
=> Ignore null-Intents in EIntentService classes

AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/Options.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/rclass/ProjectRClassFinder.java
This PR adds support to ButterKnife R2 generator plugin. Please note only the SNAPSHOT version of that plugin generates all types of resources. For rationale, see the commit message.
=> Support R2 class for resource values

AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/rclass/RInnerClass.java
The final resource values will not be the same as the compile-time values,
so we have to use the R class in the generated code, even if the user set
to use the R2 class in annotation parameters.
Follow-up fix for:
https://github.com/androidannotations/androidannotations/pull/2022
=> Use normal R class even when validating with R2

AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/helper/AndroidManifestFinder.java, AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/internal/helper/AndroidManifestFinderTest.java
This should fix https://github.com/androidannotations/androidannotations/issues/2028
@WonderCsabo  @ahornerr could you test this?
=> Update AndroidManifestFinder for Gradle builds with kapt

AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/helper/AndroidManifestFinder.java, AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/internal/helper/AndroidManifestFinderTest.java
This PR is aimed to fix #2034 and allow android annotations to work in projects that use apk splits.
=> Update Manifest finder for apk splits

AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/annotations/Background.java, AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/annotations/EActivity.java, AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/annotations/EApplication.java, AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/annotations/EBean.java, AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/annotations/EFragment.java, AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/annotations/EIntentService.java, AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/annotations/EProvider.java, AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/annotations/EReceiver.java, AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/annotations/EService.java, AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/annotations/EView.java, AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/annotations/EViewGroup.java, AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/annotations/IgnoreWhen.java, AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/annotations/SupposeBackground.java, AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/annotations/SupposeUiThread.java, AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/annotations/Trace.java, AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/annotations/Transactional.java, AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/annotations/UiThread.java, AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/annotations/WakeLock.java, AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/api/KotlinOpen.java, examples/kotlin/build.gradle, examples/kotlin/src/main/kotlin/org/androidannotations/gradle/activity/HelloAndroidActivity.kt
I should have applied the `@KotlinOpen` annotation to all annotations that override a class or method.
=> Add support for kotlin-allopen plugin

AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/holder/EActivityHolder.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/holder/EFragmentHolder.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/holder/EServiceHolder.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/holder/EViewHolder.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/holder/HasActivityLifecycleMethods.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/holder/HasSimpleLifecycleMethods.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/holder/ReceiverRegistrationDelegate.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/ReceiverHandler.java, AndroidAnnotations/androidannotations-ormlite/ormlite/src/main/java/org/androidannotations/ormlite/holder/OrmLiteHolder.java
#2048
This commit contains a bigger refactor as well: the previous
implementation contained HasLifecycleMethods interface, which was
implemented by most all the components, even if they do not have
the specific methods. This is now changed.
=> Fix IllegalStateException for @OrmLiteDao in view

AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/helper/CaseHelper.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/helper/AndroidManifestFinder.java, AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/internal/helper/AndroidManifestFinderTest.java
This PR adds support for new Manifest locations for the Android Studio 3.2 canary builds.
=> Fix manifest finder for Android Studio 3.2

AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/AndroidAnnotationProcessor.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/generation/SourceCodeWriter.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/process/ModelProcessor.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/process/ModelValidator.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/logger/Logger.java
This PR is intended to fix the logging issue mentioned in #2145 and prevent similar misuse in the future.
While the only place where this issue actually hapened where two `trace()` statements in `ModelProcessor` I refactored the log methods to have the `message` argument last or second to last if there are `args` allowed.
=> Fix logging and prevent similar issues

AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/ContextCompatAwareResHandler.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/PreferenceChangeHandler.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/handler/PreferenceClickHandler.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/core/helper/ActivityIntentBuilder.java
See #2168 
A project that is migrated to Android X no longer has support v4 classes on its classpath... at least it seems so.
One can have a project migrated to Android X and thus is no longer able to import e.g. `android.support.v4.app.Fragment` in own code. If no 3rd party library is using the support v4 fragment compiling with AA 4.5.0 is no problem. Having a 3rd party dependency that uses support v4 does not mean you can use the classes in your code as there is a tool called `jetifier` that migrates the 3rd party code on the fly to use Android X. but during the actual build process the support v4 classes are still on classpath and so available to AndroidAnnotations.
In the Android X support PR #2149 this was not known and thus we have some cases where the build fails with android x + …
=> Fix the order of some Android X checks to avoid conflicts with Support v4

AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/helper/ModelConstants.java
... as a single '_' is no longer valid in JDK 11 (and mabye 10?)
=> Check a full name instead of just the classSuffix

AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/helper/APTCodeModelHelper.java
Currently we copy all non AA annotations to the generated class. This inlcudes `kotlin.Metadata` annotation and causes some Problems, with this PR we ensure to not copy this annotation.
See https://github.com/androidannotations/androidannotations/issues/2082
=> Ensure that `kotlin.Metadata` is not copied to generated class

AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/helper/AndroidManifestFinder.java, AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/internal/helper/AndroidManifestFinderTest.java
Google once again moved the location of merged AndroidManifest.xml... this PR allows AA to find the Manifest in its new location.
Tested with `3.3.0-beta01` and `3.4.0-alpha02`
See #2173
=> Support Android Build Plugin 3.3.0-beta1

AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/Options.java, AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/helper/AndroidManifestFinder.java, AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/internal/helper/AndroidManifestFinderTest.java
Add support for Instant Apps (https://github.com/androidannotations/androidannotations/issues/2017)
While it seems that Instant Apps should already be supported for version 3.1.x of the Android Gradle Plugin. But with 3.2.x and 3.3.x changes have been made and this PR aims to ensure Instant App support for those plugins too.
For instant apps it is now required to set `"instantAppFeature": "true"` in `annotationProcessorOptions`, similar to library projects.
=> Support InstantApps, including for 3.3-beta01

AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/annotations/Background.java, AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/annotations/IgnoreWhen.java, AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/annotations/SupposeBackground.java, AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/annotations/SupposeUiThread.java, AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/annotations/Trace.java, AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/annotations/Transactional.java, AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/annotations/UiThread.java, AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/annotations/WakeLock.java
The kotlin-open is making the class and the members as well public,
so adding this annotation to member AA annotation is not needed has
no effect.
=> Add @KotlinOpen to class annotations only

AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/helper/AndroidManifestFinder.java, AndroidAnnotations/androidannotations-core/androidannotations/src/test/java/org/androidannotations/internal/helper/AndroidManifestFinderTest.java
Google updated the generated code folder for Java Builds and with this PR we support those new folders for Manifest detection. :)
Fixes https://github.com/androidannotations/androidannotations/issues/2229.
=>  Support Android Gradle Plugin 3.5.0-beta03 and 3.6.0-alpha01
